2024-09-02 16:01:58,154 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-09-02 16:01:58,154 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Configure stats pid to 19220
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Loading settings from C:\Users\LimJaesung\.config\wandb\settings
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Loading settings from C:\Users\LimJaesung\Documents\Git\VAE\convVAE\wandb\settings
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'convVAE\\inference.py', 'program_abspath': 'C:\\Users\\LimJaesung\\Documents\\Git\\VAE\\convVAE\\inference.py', 'program': 'C:\\Users\\LimJaesung\\Documents\\Git\\VAE\\convVAE\\inference.py'}
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\LimJaesung\Documents\Git\VAE\convVAE\wandb\run-20240902_160158-qwdlozy0\logs\debug.log
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\LimJaesung\Documents\Git\VAE\convVAE\wandb\run-20240902_160158-qwdlozy0\logs\debug-internal.log
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:init():607] calling init triggers
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:init():657] starting backend
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:init():661] setting up manager
2024-09-02 16:01:58,169 INFO    MainThread:19220 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-09-02 16:01:58,169 INFO    MainThread:19220 [wandb_init.py:init():669] backend started and connected
2024-09-02 16:01:58,184 INFO    MainThread:19220 [wandb_init.py:init():767] updated telemetry
2024-09-02 16:01:58,305 INFO    MainThread:19220 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-09-02 16:01:58,779 WARNING MainThread:19220 [wandb_init.py:init():1232] interrupted
Traceback (most recent call last):
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\site-packages\wandb\sdk\wandb_init.py", line 1228, in init
    return wi.init()
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\site-packages\wandb\sdk\wandb_init.py", line 803, in init
    result = run_init_handle.wait(
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\LimJaesung\anaconda3\envs\impute\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-09-02 16:02:05,215 WARNING MsgRouterThr:19220 [router.py:message_loop():77] message_loop has been closed
